---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spleen-seg-test-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-test-data-populator
  labels:
    app: ephemeral-test-data-populator
spec:
  volumes:
    - name: spleen-seg-test-data
      persistentVolumeClaim:
        claimName: spleen-seg-test-data
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: httpd
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: "/mnt/spleen-seg-test-data"
          name: spleen-seg-test-data
